config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :clients
  resources :people
  resources :contacts

  root :to => redirect('/clients')

end

app/models/person.rb
class Person < ActiveRecord::Base
  enum person_type: {fisic: 0, juridic: 1}
  has_many :invoices, dependent: :restrict_with_error
  has_many :clients, through: :invoices

  validates :name,
    presence: true,
    format: { with: /\A[\p{L}\s.]+\z/ },
    length: { minimum: 2, maximum: 30 }

  validates :person_type,
    presence: true,
    inclusion: { in: self.person_types.keys }

  validates :cuilt,
    presence: true,
    uniqueness: true,
    format: { with: /\A\d{2}\-\d{8}\-\d{1}\z/ }

  def to_s
    "#{self.name} (#{self.cuilt})"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    msg = t 'person_cannot_be_deleted'
    if @person.destroy
      msg = t 'person_was_successfully_destroyed.'
    end
    respond_to do |format|
      format.html { redirect_to people_url, notice: msg }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :person_type, :cuilt)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= simple_form_for(@person) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :person_type, :as => :select, :collection => Person.person_types.keys %>
    <%= f.input :cuilt %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-success', value: t('save') %>
    <%= link_to t('back'), people_path, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <h1><%= t "edit_person" %></h1>
  <hr>
  <%= render 'form' %>
</div>

app/views/people/index.html.erb
<div class="col-sm-8 col-sm-offset-2">

  <div class="row">
    <%= render template: 'shared/_notices' %>
  </div>

  <div class="row pull-right">
    <%= link_to t('new_person'), new_person_path, :class => 'btn btn-sm btn-success' %>
  </div>

  <hr>

  <div class="row">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th><%= t "name" %></th>
          <th><%= t "person_type" %></th>
          <th><%= t "cuil_cuit" %></th>
          <th><%= t "actions" %></th>
        </tr>
      </thead>
      <tbody>
        <% @people.each do |person| %>
          <tr>
            <td><%= person.name %></td>
            <td><%= person.person_type %></td>
            <td><%= person.cuilt %></td>
            <td>
              <%= render template: 'shared/_actions', locals: {model: person} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/people/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <h1><%= t('new_person') %></h1>
  <hr>
  <%= render 'form' %>
</div>

app/views/people/show.html.erb
<div class="col-sm-10 col-sm-offset-1">
  <div class="row">
    <%= render template: 'shared/_notices' %>
  </div>

  <div class="row bg-info clearfix">
    <div class="pull-left">
      <%= link_to t('back'), people_path, :class => 'btn btn-sm btn-default' %>
    </div>
    <div class="pull-right">
      <%= link_to t('edit'), edit_person_path(@person), :class => 'btn btn-sm btn-warning' %>
    </div>
  </div>
  <hr>
  <div class="col-md-6 col-md-offset-3">
    <table class="table">
      <thead>
        <tr>
          <th><%= t('name') %></th>
          <th><%= t('person_type') %></th>
          <th><%= t('cuil_cuit') %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @person.name %></td>
          <td><%= @person.person_type %></td>
          <td><%= @person.cuilt %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>