config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :clients
  resources :people
  resources :contacts

  root :to => redirect('/clients')

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  belongs_to :person

  validates :client, :person,
    presence: true

  validates :issue_date,
    presence: true,
    date: {
      after: Proc.new { Time.now - 10.year },
      before: Proc.new { Time.now + 50.year }
    }

  validates :description,
    presence: true,
    length: { minimum: 2 }

  validates :amount,
    presence: true,
    numericality: { greater_than_or_equal_to: 1.00}
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:description, :amount, :issue_date, :client_id, :person_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= simple_form_for(@invoice) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :amount %>
    <%= f.input :issue_date %>
    <%= f.association :client %>
    <%= f.association :person %>
  </div>

  <div class="actions">
    <%= f.button :submit, :value => t('save') %>
    <%= link_to t('back'), invoices_path, :class => 'btn btn-danger' %>
  </div>

<% end %>

app/views/invoices/edit.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <h1><%= t('edit_invoice') %></h1>
  <hr>
  <%= render 'form' %>
</div>

app/views/invoices/index.html.erb
<div class="col-sm-12">

  <div class="row">
    <%= render template: 'shared/_notices' %>
  </div>

  <div class="row pull-right">
    <%= link_to t('new_invoice'), new_invoice_path, :class => 'btn btn-sm btn-success' %>
  </div>

  <hr>

  <div class="row">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th><%= t "description" %></th>
          <th><%= t "amount" %></th>
          <th><%= t "issue_date" %></th>
          <th><%= t "client" %></th>
          <th><%= t "person" %></th>
          <th><%= t "actions" %></th>
        </tr>
      </thead>
      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.description %></td>
            <td><%= number_to_currency(invoice.amount, precision: 2) %></td>
            <td><%= t invoice.issue_date, format: :default %></td>
            <td><%= invoice.client.full_name %></td>
            <td><%= invoice.person.name %></td>
            <td>
              <%= render template: 'shared/_actions', locals: {model: invoice} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/invoices/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <h1><%= t('new_invoice') %></h1>
  <hr>
  <%= render 'form' %>
</div>

app/views/invoices/show.html.erb
<div class="col-sm-10 col-sm-offset-1">
  <div class="row">
    <%= render template: 'shared/_notices' %>
  </div>

  <div class="row bg-info">
    <div class="pull-left">
      <%= link_to t('back'), invoices_path, :class => 'btn btn-sm btn-default' %>
    </div>
    <div class="pull-right">
      <%= link_to t('edit'), edit_invoice_path(@invoice), :class => 'btn btn-sm btn-warning' %>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th><%= t('description') %></th>
          <th><%= t('amount') %></th>
          <th><%= t('issue_date') %></th>
          <th><%= t('client') %></th>
          <th><%= t('person') %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @invoice.description %></td>
          <td><%= @invoice.amount %></td>
          <td><%= @invoice.issue_date %></td>
          <td><%= @invoice.client %></td>
          <td><%= @invoice.person %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>