config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :clients
  resources :people
  resources :contacts

  root :to => redirect('/clients')

end

app/models/client.rb
class Client < ActiveRecord::Base
  enum genre: {male: 0, female: 1}
  has_many :clients_contacts, inverse_of: :client
  has_many :contacts, through: :clients_contacts
  accepts_nested_attributes_for :clients_contacts, :allow_destroy => true
  has_many :invoices, dependent: :restrict_with_error
  has_many :people, through: :invoices

  validates :firstname, :lastname,
    presence: true,
    format: { with: /\A[\p{L}\s.]+\z/ },
    length: { minimum: 2, maximum: 30 }

  validates :genre,
    presence: true,
    inclusion: { in: self.genres.keys }

  validates :birthdate,
    presence: true,
    date: {
      after: Proc.new { Time.now - 100.year },
      before: Proc.new { Time.now - 18.year }
    }

  validates :cuilt,
    presence: true,
    format: { with: /\A\d{2}\-\d{8}\-\d{1}\z/ },
    uniqueness: true

  validates :identification_number,
    presence: true,
    numericality: { only_integer: true },
    format: { with: /\A[0-9]+\z/ },
    length: { minimum: 6, maximum: 8 }

  # Total of invoices on current year grouped by months
  def total_invoices_current_year_by_month
    self.invoices
      .select("strftime('%m', issue_date) as month, COUNT(*) as total")
      .where("strftime('%Y', issue_date) = ?", Time.now.year.to_s)
      .group("strftime('%m', issue_date)")
      .order("strftime('%m', issue_date)")
  end

  # Amount total of invoices on current year
  def amount_total_invoices_by_year
    self.invoices
      .select("strftime('%Y', issue_date) as year, ROUND(SUM(amount),2) as total")
      .group("strftime('%Y', issue_date)")
      .order("strftime('%Y', issue_date)")
  end

  # Most invoiced people
  def most_invoiced_people(limit)
    self.people
      .select("people.id as pid, people.name as name, COUNT(*) as total, ROUND(SUM(amount),2) as amount")
      .group("people.id")
      .order("amount DESC")
      .limit(limit)
  end

  def full_name
    "#{self.firstname} #{self.lastname}"
  end

  def age
    age = Date.today.year - self.birthdate.year
    # for days before birthday
    age -= 1 if Date.today < self.birthdate + age.years
    age.to_i
  end

  def age_s
    "#{self.age.to_s} " << (I18n.t("years"))
  end

  def to_s
    "#{self.full_name} (#{self.identification_number})"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @invoices_current_year = @client.total_invoices_current_year_by_month
    @amount_total_invoices_by_year = @client.amount_total_invoices_by_year
    @most_invoiced_people = @client.most_invoiced_people(5)
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: t('client_was_successfully_created') }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: t('client_was_successfully_updated') }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    msg = t 'client_cannot_be_deleted'
    if @client.destroy
      msg = t 'client_was_successfully_destroyed.'
    end
    respond_to do |format|
      format.html { redirect_to clients_url, notice: msg }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params
        .require(:client)
        .permit(
          :firstname, :lastname, :birthdate,
          :genre, :identification_number,
          :cuilt, clients_contacts_attributes: [:id, :contact_id, :value, :_destroy])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def profile_placeholder(client)
    image_tag "placeholder_#{client.genre}.jpg", :class => 'img-circle img-thumbnail profile-img'
  end
end

app/views/clients/_form.html.erb
<%= simple_nested_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :birthdate, html5: true, dateformat:'dd/mm/yyyy' %>
    <%= f.input :genre, collection: Client.genres.keys, prompt: :translate %>
    <%= f.input :identification_number %>
    <%= f.input :cuilt %>
    <label><%= t "contact_types" %></label>
    <p><%= f.link_to_add t("new_contact"), :clients_contacts, :class => 'btn btn-sm btn-success', :data => { :target => "#clients_contacts" } %></p>
    <table class="table" id="clients_contacts">
      <%= f.fields_for :clients_contacts, :wrapper => false do |cc| %>
        <tr class="fields">
          <td><%= cc.input :contact_id, collection: Contact.all, include_blank: false %></td>
          <td><%= cc.input :value %></td>
          <td><%= cc.link_to_remove t"remove" %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-success', value: t('save') %>
    <%= link_to t('back'), clients_path, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <h1><%= t "edit_client" %></h1>
  <hr>
  <%= render 'form' %>
</div>

app/views/clients/index.html.erb
<div class="col-sm-10 col-sm-offset-1">

  <div class="row">
    <%= render template: 'shared/_notices' %>
  </div>

  <div class="row pull-right">
    <%= link_to t('new_client'), new_client_path, :class => 'btn btn-sm btn-success' %>
  </div>

  <hr>

  <div class="row">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th><%= t "firstname" %></th>
          <th><%= t "lastname" %></th>
          <th><%= t "birthdate" %></th>
          <th><%= t "genre" %></th>
          <th><%= t "identification_number" %></th>
          <th><%= t "cuil_cuit" %></th>
          <th><%= t "actions" %></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.firstname %></td>
            <td><%= client.lastname %></td>
            <td><%= client.birthdate %></td>
            <td><%= client.genre %></td>
            <td><%= client.identification_number %></td>
            <td><%= client.cuilt %></td>
            <td>
              <%= render template: 'shared/_actions', locals: {model: client} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clients/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <h1><%= t "new_client" %></h1>
  <hr>
  <%= render 'form' %>
</div>

app/views/clients/show.html.erb
<div class="col-sm-10 col-sm-offset-1">
  <div class="row">
    <%= render template: 'shared/_notices' %>
  </div>

  <div class="row bg-info">
    <div class="pull-left">
      <%= link_to t('back'), clients_path, :class => 'btn btn-sm btn-default' %>
    </div>
    <div class="pull-right">
      <%= link_to t('edit'), edit_client_path(@client), :class => 'btn btn-sm btn-warning' %>
    </div>
  </div>

  <hr>

  <div class="row jumbotron">
    <div class="pull-right">
      <button class="btn btn-sm btn-info toggler" type="button" data-show="#contacts" data-hide="#meta-info">Contactar</button>
    </div>
    <div class="pull-left">
      <%= profile_placeholder @client %>
    </div>
    <div class="col-sm-8">
      <div class="hidden" id="contacts">
        <% if @client.clients_contacts.count > 0 %>
          <p>Medios de contacto:</p>
          <ul class="list-group">
            <% @client.clients_contacts.each do |cc| %>
            <li class="list-group-item">
              <strong><%= cc.contact.name.capitalize %>:</strong>
              <%= cc.value %>
            </li>
            <% end %>
          </ul>
        <% else %>
          <p>No tiene medios de contacto</p>
        <% end %>
      </div><!-- #contacts -->
      <div id="meta-info">
        <h1><%= @client.full_name %> <small class="years_old">(<%= @client.age_s %>)</small></h1>
        <p>
          <strong><%= t 'cuil_cuit' %>:</strong>
          <%= @client.cuilt %>
        </p>
        <p>
          <strong><%= t 'identification_number' %>:</strong>
          <%= @client.identification_number %>
        </p>
        <p>
          <strong><%= t 'genre' %>:</strong>
          <%= t @client.genre %>
        </p>
      </div><!-- #meta-info -->
    </div>
  </div>

  <div class="row">
    <h2>Facturado por año</h2>
    <hr>
    <table class="table table-bordered">
      <tbody>
        <% if @amount_total_invoices_by_year.each do |ay| %>
          <tr>
            <td><%= "En #{ay.year} facturó #{number_to_currency(ay.total, precision: 2)}" %></td>
          </tr>
        <% end.empty? %>
          <tr>
            <td>No posee facturas</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <h2>Total de facturas por mes del año <%= Time.now.year %></h2>
    <hr>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th><%= t "month" %></th>
          <th><%= t "total_invoices" %></th>
        </tr>
      </thead>
      <tbody>
        <% if @invoices_current_year.each do |icy| %>
          <tr>
            <td><%= get_month_name(icy.month) %></td>
            <td><%= icy.total %></td>
          </tr>
        <% end.empty? %>
          <tr>
            <td>-</td>
            <td>-</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <h2>Personas a las que más se le ha facturado</h2>
    <hr>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th><%= t "name" %></th>
          <th><%= t "amount" %></th>
          <th><%= t "total_invoices" %></th>
        </tr>
      </thead>
      <tbody>
        <% if @most_invoiced_people.each do |mip| %>
          <tr>
            <td><%= mip.name %></td>
            <td>$<%= mip.amount %></td>
            <td><%= mip.total %></td>
          </tr>
        <% end.empty? %>
          <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>